#!/usr/bin/env bash
set -euo pipefail

BASE_URL="${SIMPLE_AI_BASE_URL:-http://localhost:8081}"
MODEL="${SIMPLE_AI_TTS_MODEL:-xtts-v2}"
VOICE="${SIMPLE_AI_TTS_VOICE:-Ana Florence}"
FORMAT="${1:-wav}"
OUTPUT="${2:-tts-sample.$FORMAT}"
TEXT="${3:-This is a text to speech sample generated by simple-ai.}"

if [[ -z "${SIMPLE_AI_API_KEY:-}" ]]; then
  echo "SIMPLE_AI_API_KEY is required" >&2
  exit 1
fi

jq -n \
  --arg model "$MODEL" \
  --arg input "$TEXT" \
  --arg voice "$VOICE" \
  --arg response_format "$FORMAT" \
  '{model: $model, input: $input, voice: $voice, response_format: $response_format}' \
  | curl -sS -f "$BASE_URL/v1/audio/speech" \
      -H "Authorization: Bearer $SIMPLE_AI_API_KEY" \
      -H "Content-Type: application/json" \
      --data-binary @- \
      -o "$OUTPUT"

file "$OUTPUT"
